### ISSUE TITLE
does this support bi-directional sync?

### ISSUE THREAD

**Issue by distbit0** [gavindsouza/md2docs#1]

**Comment by gavindsouza** [comment]
No, this only caters to copying local file to gdocs. Also, it doesn't just update the diff but rewrite the whole file so GDocs History feature may not work accurately.

**Comment by distbit0** [comment]
do you by any chance know of any tools which support bi-directional sync between local md files and any online collaborative text editor? many thx

**Comment by gavindsouza** [comment]
Probably [Obsidian](https://obsidian.md/sync)?

**Comment by distbit0** [comment]
Ah yeah I should have mentioned I am interested in something editor-independent/cli-based. I previously used obsidian but prefer doing everything via vscode these days instead of having separate editors for writing code and writing markdown.

anyway, appreciate you help :)
